### ISSUE TITLE
non-existent rule file - allow the tool to start

### ISSUE THREAD

**Issue by rmlockwood** [AndyBlack/ftrulegen#9]
It would be nice if the Rule Assistant would start up with a default blank rule when the rule file name given to the tool doesn't exist. Any time the user clicks save, the rule file would then get created. This will help a lot when a user is just starting and we don't have to have a "blank" rule file for him/her to start with. It also could be that the rule file gets deleted at some point and the tool should still function. Right now with a non-existent rule file, nothing happens. The tool doesn't start.

**Comment by AndyBlack** [comment]
I was thinking that FLExTrans would be the maintainer of this file; that is, it knows where it lives.  If there isn't one yet, FT will create it and pass it to the Rule Assistant.  The Rule Assistant does not keep track of that.  If it did, it would have to notify FLExTrans when a new file was made.  How would we do that?

**Comment by rmlockwood** [comment]
I agree that FT maintains the file, but it is a little problematic to know what the format of the file should be. That might change from time to time, but the RA would know what the format should be. So I thought that if a path is passed to the RA, but that file doesn't yet exist, the RA would create it at that exact path. It could either create it on start up or maybe the first time the user hits Save.
________________________________

**Comment by AndyBlack** [comment]
Fixed
